dist: bionic
language: cpp
env:
  global:
    - BOOST_TEST_COLOR_OUTPUT=yes
    - BOOST_TEST_LOG_LEVEL=test_suite
    - PATCHSET_NDNCXX=master
  matrix:
    - PROJECT=NFD
    - PROJECT=ChronoSync
    - PROJECT=PSync
    - PROJECT=NLSR
    - PROJECT=name-based-access-control
    - PROJECT=ndncert
    - PROJECT=ndns
    - PROJECT=ndn-tools
    - PROJECT=ndn-traffic-generator
    - PROJECT=repo-ng
install:
  - DEPS=$(sort -u ndn-cxx.deps ${PROJECT}.deps)
  - sudo apt-get update -qq
  - sudo apt-get install -qy ${DEPS}
before_script:
  - sudo sysctl -e -w net.ipv6.conf.all.disable_ipv6=0
  - ./build_ndn-cxx.sh
script:
  - ./build_${PROJECT}.sh
