version: ~> 1.0
language: cpp
os: linux
dist: bionic
jobs:
  include:
    - name: NFD
      env: PROJECT=NFD
    - name: ChronoSync
      env: PROJECT=ChronoSync
    - name: PSync
      env: PROJECT=PSync
    - name: NLSR
      env: PROJECT=NLSR
    - name: name-based-access-control
      env: PROJECT=name-based-access-control
    - name: ndncert
      env: PROJECT=ndncert
    - name: ndns
      env: PROJECT=ndns
    - name: ndn-tools
      env: PROJECT=ndn-tools
    - name: ndn-traffic-generator
      env: PROJECT=ndn-traffic-generator
    - name: repo-ng
      env: PROJECT=repo-ng
install:
  - DEPS=$(sort -u ndn-cxx.deps ${PROJECT}.deps)
  - sudo apt-get update -qq
  - sudo apt-get install -qy ${DEPS}
before_script:
  - sudo sysctl -e -w net.ipv6.conf.all.disable_ipv6=0
  - export BOOST_TEST_COLOR_OUTPUT=yes
  - export BOOST_TEST_LOG_LEVEL=test_suite
  - ./build_ndn-cxx.sh
script:
  - ./build_${PROJECT}.sh
